name: JestStatus


on: [push]
  
jobs:
 testing_repository:
  
  runs-on: ubuntu-latest

  steps:
  - name: git clone my repository
    uses: actions/checkout@v1
    
  - name: install packages
    run: make install

  - name: testing(JEST)
    run: make test
  
  - name: test-coverage
    uses: korolmaria/codeclimate-action@v2.7.4
        # Add Code Climate secret key
    env: 
      TESTREPORTER_ID: ${{ secrets.TESTREPORTER_ID }}
    with:
      coverageCommand: make test-coverage
      debug: true
    