name: JestStatus


on: [push]
  
jobs:
 testing_repository:
  
  runs-on: ubuntu-latest

  steps:
  - name: git clone my repository
    uses: actions/checkout@v1
    
  - name: install packages
    run: make install

  - name: testing(JEST)
    run: make test
  
  - name: test-coverage
    env: 
      TESTREPORTER_ID: ${{ secrets.TESTREPORTER_ID }}
    run: make test-coverage
