name: JestStatus


on: [push]
  
jobs:
 testing_repository:
  
  runs-on: ubuntu-latest

  steps:
  - name: git clone my repository
    uses: actions/checkout@v1
    
  - name: install packages
    run: make install

  - name: testing(JEST)
    run: make test

  - name: test-coverage
    uses: korolmaria/frontend-project-lvl2@v2.7.1
        # Add Code Climate secret key
    env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    with:
        coverageCommand: make test-coverage
        debug: true
