name: JestStatus


on: [push]
  
jobs:
 testing_repository:
  
  runs-on: ubuntu-latest

  steps:
  - name: git clone my repository
    uses: actions/checkout@v1
    
  - name: install packages
    run: make install

  - name: testing(JEST)
    run: make test
  
  - name: test-coverage
    env: 
      TESTREPORTER_ID: ${{ secrets.TESTREPORTER_ID }}
<<<<<<< HEAD
    run: make test-coverage
    
=======
    with:
      coverageCommand: make test-coverage
      debug: true
    
>>>>>>> b265fc25c8cb4eb424d261cff52a72a3e0159358
